"""
language_codes.py

This module contains a comprehensive language_mapping dictionary that stores
primarily major languages, which are recognized by international bodies like
ISO 639-1 or ISO 639-2. These languages are standardized.
"""

language_mapping = {
    "Abkhazian": "ab",
    "Afar": "aa",
    "Afrikaans": "af",
    "Akan": "ak",
    "Albanian": "sq",
    "Amharic": "am",
    "Arabic": "ar",
    "Aragonese": "an",
    "Armenian": "hy",
    "Assamese": "as",
    "Avaric": "av",
    "Avestan": "ae",
    "Aymara": "ay",
    "Azerbaijani": "az",
    "Bambara": "bm",
    "Bashkir": "ba",
    "Basque": "eu",
    "Belarusian": "be",
    "Bengali": "bn",
    "Bihari languages": "bh",
    "Bislama": "bi",
    "Bosnian": "bs",
    "Breton": "br",
    "Bulgarian": "bg",
    "Burmese": "my",
    "Catalan, Valencian": "ca",
    "Chamorro": "ch",
    "Chechen": "ce",
    "Chichewa, Chewa, Nyanja": "ny",
    "Chinese": "zh",
    "Chuvash": "cv",
    "Cornish": "kw",
    "Corsican": "co",
    "Cree": "cr",
    "Croatian": "hr",
    "Czech": "cs",
    "Danish": "da",
    "Divehi, Dhivehi, Maldivian": "dv",
    "Dutch, Flemish": "nl",
    "Dzongkha": "dz",
    "English": "en",
    "Esperanto": "eo",
    "Estonian": "et",
    "Ewe": "ee",
    "Faroese": "fo",
    "Fijian": "fj",
    "Finnish": "fi",
    "French": "fr",
    "Fulah": "ff",
    "Galician": "gl",
    "Ganda": "lg",
    "Georgian": "ka",
    "German": "de",
    "Greek (modern)": "el",
    "Guarani": "gn",
    "Gujarati": "gu",
    "Haitian, Haitian Creole": "ht",
    "Hausa": "ha",
    "Hebrew": "he",
    "Herero": "hz",
    "Hindi": "hi",
    "Hiri Motu": "ho",
    "Hungarian": "hu",
    "Icelandic": "is",
    "Ido": "io",
    "Igbo": "ig",
    "Indonesian": "id",
    "Interlingua (International Auxiliary Language Association)": "ia",
    "Interlingue, Occidental": "ie",
    "Inuktitut": "iu",
    "Inupiaq": "ik",
    "Irish": "ga",
    "Italian": "it",
    "Japanese": "ja",
    "Javanese": "jv",
    "Kalaallisut, Greenlandic": "kl",
    "Kannada": "kn",
    "Kanuri": "kr",
    "Kashmiri": "ks",
    "Kazakh": "kk",
    "Khmer": "km",
    "Kikuyu, Gikuyu": "ki",
    "Kinyarwanda": "rw",
    "Kirghiz, Kyrgyz": "ky",
    "Komi": "kv",
    "Kongo": "kg",
    "Korean": "ko",
    "Kurdish": "ku",
    "Kwanyama, Kuanyama": "kj",
    "Lao": "lo",
    "Latin": "la",
    "Latvian": "lv",
    "Limburgan, Limburger, Limburgish": "li",
    "Lingala": "ln",
    "Lithuanian": "lt",
    "Luba-Katanga": "lu",
    "Luxembourgish, Letzeburgesch": "lb",
    "Macedonian": "mk",
    "Malagasy": "mg",
    "Malay": "ms",
    "Malayalam": "ml",
    "Maltese": "mt",
    "Manx": "gv",
    "Maori": "mi",
    "Marathi": "mr",
    "Marshallese": "mh",
    "Moldovan, Moldavian, Romanian": "ro",
    "Mongolian": "mn",
    "Nauru": "na",
    "Navajo, Navaho": "nv",
    "Ndebele, South, Ndebele": "nr",
    "Ndebele, North, North Ndebele": "nd",
    "Ndonga": "ng",
    "Nepali": "ne",
    "Northern Sami": "se",
    "Norwegian": "no",
    "Norwegian Bokmål": "nb",
    "Norwegian Nynorsk": "nn",
    "Occitan (post 1500)": "oc",
    "Ojibwa": "oj",
    "Oriya": "or",
    "Oromo": "om",
    "Ossetian, Ossetic": "os",
    "Pali": "pi",
    "Panjabi, Punjabi": "pa",
    "Pashto, Pushto": "ps",
    "Persian": "fa",
    "Polish": "pl",
    "Portuguese": "pt",
    "Quechua": "qu",
    "Romanian, Moldavian, Moldovan": "ro",
    "Romansh": "rm",
    "Rundi": "rn",
    "Russian": "ru",
    "Samoan": "sm",
    "Sango": "sg",
    "Sanskrit": "sa",
    "Sardinian": "sc",
    "Serbian": "sr",
    "Shona": "sn",
    "Sichuan Yi, Nuosu": "ii",
    "Sindhi": "sd",
    "Sinhala, Sinhalese": "si",
    "Slovak": "sk",
    "Slovenian": "sl",
    "Somali": "so",
    "Sotho, Southern": "st",
    "South Ndebele": "nr",
    "Spanish, Castilian": "es",
    "Sundanese": "su",
    "Swahili": "sw",
    "Swati": "ss",
    "Swedish": "sv",
    "Tagalog": "tl",
    "Tahitian": "ty",
    "Tajik": "tg",
    "Tamil": "ta",
    "Tatar": "tt",
    "Telugu": "te",
    "Thai": "th",
    "Tibetan": "bo",
    "Tigrinya": "ti",
    "Tonga (Tonga Islands)": "to",
    "Tsonga": "ts",
    "Tswana": "tn",
    "Turkish": "tr",
    "Turkmen": "tk",
    "Twi": "tw",
    "Uighur, Uyghur": "ug",
    "Ukrainian": "uk",
    "Urdu": "ur",
    "Uzbek": "uz",
    "Venda": "ve",
    "Vietnamese": "vi",
    "Volapük": "vo",
    "Walloon": "wa",
    "Welsh": "cy",
    "Western Frisian": "fy",
    "Wolof": "wo",
    "Xhosa": "xh",
    "Yiddish": "yi",
    "Yoruba": "yo",
    "Zhuang, Chuang": "za",
    "Zulu": "zu"
}